name: Deploy Frontend to AWS ECS

on:
  push:
    branches:
      - staging  # Runs when frontend repo is updated

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "ap-south-1"
      ECS_CLUSTER: "staging-cluster"
      ECS_SERVICE_FRONTEND: "pos-frontend"

    steps:
      # 1️⃣ Checkout the Repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2️⃣ Clone `pos-frontend` Repository
      - name: Clone pos-frontend Repository
        run: |
          git clone https://github.com/POS-Developers/pos-frontend.git
          ls -l pos-frontend  # Debug to confirm folder exists

      # 3️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Build & Push Frontend Image
      - name: Build and Push Frontend Image
        run: |
          cd pos-frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest

      # 5️⃣ Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 6️⃣ Force ECS to Pull Latest Frontend Image
      - name: Force ECS Service Update
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE_FRONTEND --force-new-deployment
